{% set version="13.46.1.b8b01e06" %}

package:
  name: t_coffee
  version: {{ version }}

source:
  url: https://s3.eu-central-1.amazonaws.com/tcoffee-packages/Archives/T-COFFEE_distribution_Version_{{ version }}.tar.gz
  sha256: 081be54f86723fb09e5db05443ba97d08bc4f53d07d4673c8f7bc142c2587041

requirements:
  build:
    - zlib
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

test:
  commands:
    - t_coffee -version | grep -q {{ version }}

