{% set version="13.46.1.b8b01e06" %}

package:
  name: t_coffee
  version: {{ version }}

source:
  url: https://s3.eu-central-1.amazonaws.com/tcoffee-packages/Archives/T-COFFEE_distribution_Version_{{ version }}.tar.gz
  sha256: 54d2b00956af79a884fe7174522522c77e65796d5aa08974dad86e061e6d12d1

requirements:
  build:
    - zlib
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

test:
  commands:
    - t_coffee -version | grep -q {{ version }}

